server:
  port: 6321


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://121.37.185.55:3306/note?allowMultiQueries=true&characterEncoding=utf-8
  servlet:
    multipart:
      max-file-size: 20MB


mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.dygticky.cnoteserver.model


file:
  upload-dir: ./uploads


